import React from 'react';

function Table() {
    return (
        <>
            <div id="total_table_wrap">
                <table id="total_table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>first name</th>
                            <th>last name</th>
                            <th>email</th>
                            <th>totalBeforeTaxAdditions</th>
                            <th>totalBeforeTaxDeductions</th>
                            <th>calculatedTax</th>
                            <th>totalAfterTaxAdditions</th>
                            <th>totalAfterTaxDeductions</th>
                            <th>totalNet</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td>Johnny</td>
                            <td>Bravo</td>
                            <td>whoamomma@acme.com</td>
                            <td>375</td>
                            <td>0</td>
                            <td>300</td>
                            <td>0</td>
                            <td>48</td>
                            <td>177</td>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>Johnny</td>
                            <td>Bravo</td>
                            <td>whoamomma@acme.com</td>
                            <td>375</td>
                            <td>0</td>
                            <td>300</td>
                            <td>0</td>
                            <td>48</td>
                            <td>177</td>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>Johnny</td>
                            <td>Bravo</td>
                            <td>whoamomma@acme.com</td>
                            <td>375</td>
                            <td>0</td>
                            <td>300</td>
                            <td>0</td>
                            <td>48</td>
                            <td>177</td>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>Johnny</td>
                            <td>Bravo</td>
                            <td>whoamomma@acme.com</td>
                            <td>375</td>
                            <td>0</td>
                            <td>300</td>
                            <td>0</td>
                            <td>48</td>
                            <td>177</td>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>Johnny</td>
                            <td>Bravo</td>
                            <td>whoamomma@acme.com</td>
                            <td>375</td>
                            <td>0</td>
                            <td>300</td>
                            <td>0</td>
                            <td>48</td>
                            <td>177</td>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>Johnny</td>
                            <td>Bravo</td>
                            <td>whoamomma@acme.com</td>
                            <td>375</td>
                            <td>0</td>
                            <td>300</td>
                            <td>0</td>
                            <td>48</td>
                            <td>177</td>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>Johnny</td>
                            <td>Bravo</td>
                            <td>whoamomma@acme.com</td>
                            <td>375</td>
                            <td>0</td>
                            <td>300</td>
                            <td>0</td>
                            <td>48</td>
                            <td>177</td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td>BLANK</td>
                            <td>TOTAL</td>
                            <td>TOTAL</td>
                            <td>TOTAL</td>
                            <td>TOTAL</td>
                            <td>TOTAL</td>
                            <td>TOTAL</td>
                            <td>TOTAL</td>
                            <td>TOTAL</td>
                            <td>TOTAL</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </>
    );
}

export default Table;
